name: dart_express
version: 1.0.4
description: >-
  Api Server inspired in expressjs implement in pure dart
homepage: https://github/mhliebano/dartExpress
documentation: https://github/mhliebano/dartExpress/doc
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  crypto: ^3.0.1
