name: dear
version: 1.0.10+21
description: >-
  Api Server inspired in expressjs implement in pure dart, Dart Easy Api Rest (DEAR)
homepage: https://github.com/mhliebano/dartExpress
documentation: https://github.com/mhliebano/dartExpress/wiki
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  crypto: ^3.0.1
