name: dartExpress
version: 1.0.0
description: >-
  Api Server inspired in expressjs implement in pure dart
homepage: https://github/mhliebano/servant
documentation: https://github/mhliebano/servant/doc
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.1
